#pragma once

#include <rgblight_list.h>

#ifdef RGBLIGHT_ENABLE
#define MG_BASE_COLOR HSV_SPRINGGREEN
#else
#define MG_BASE_COLOR HSV_YELLOW
#endif
#define MG_LAYER_CAPSLOCK_COLOR HSV_RED
#define MG_LAYER_1_COLOR HSV_BLUE
#define MG_LAYER_2_COLOR HSV_PURPLE
#define MG_LAYER_3_COLOR HSV_MAGENTA

#define MG_LAYER_INDICATOR_ONLY_MAPPED 1

#define _GET_H(H, S, V, INDEX, ...) H
#define _GET_S(H, S, V, INDEX, ...) S
#define _GET_INDEX(H, S, V, INDEX, ...) INDEX

#define MG_HSV_TO_BACKLIGHT_CONFIG_INDICATOR(...) { .color = { .h = _GET_H(__VA_ARGS__), .s = _GET_S(__VA_ARGS__) }, .index = _GET_INDEX(__VA_ARGS__) }
#define MG_HSV_TO_HS(...) { .h = _GET_H(__VA_ARGS__), .s = _GET_S(__VA_ARGS__) }

#ifdef MG_BASE_COLOR
  #undef RGB_BACKLIGHT_COLOR_1
  #define RGB_BACKLIGHT_COLOR_1 MG_HSV_TO_HS(MG_BASE_COLOR, 0)
#endif


#undef RGB_BACKLIGHT_DISABLE_AFTER_TIMEOUT
#define RGB_BACKLIGHT_DISABLE_AFTER_TIMEOUT 3

#undef RGB_BACKLIGHT_DISABLE_WHEN_USB_SUSPENDED
#define RGB_BACKLIGHT_DISABLE_WHEN_USB_SUSPENDED 1

#undef RGB_BACKLIGHT_DISABLE_AFTER_TIMEOUT
#define RGB_BACKLIGHT_DISABLE_AFTER_TIMEOUT 3

#undef RGB_BACKLIGHT_BRIGHTNESS
#define RGB_BACKLIGHT_BRIGHTNESS 100

/* enable/disable LEDs based on layout */
#undef RGB_BACKLIGHT_EFFECT
#define RGB_BACKLIGHT_EFFECT 12

#undef MG_RGBLIGHT_EFFECT
#define MG_RGBLIGHT_EFFECT RGBLIGHT_MODE_STATIC_LIGHT

#undef RGB_BACKLIGHT_EFFECT_SPEED
#define RGB_BACKLIGHT_EFFECT_SPEED 0

#undef RGB_BACKLIGHT_LAYER_1_INDICATOR
#define RGB_BACKLIGHT_LAYER_1_INDICATOR MG_HSV_TO_BACKLIGHT_CONFIG_INDICATOR(MG_LAYER_1_COLOR, 254)

#undef RGB_BACKLIGHT_LAYER_2_INDICATOR
#define RGB_BACKLIGHT_LAYER_2_INDICATOR MG_HSV_TO_BACKLIGHT_CONFIG_INDICATOR(MG_LAYER_2_COLOR, 254)

#undef RGB_BACKLIGHT_LAYER_3_INDICATOR
#define RGB_BACKLIGHT_LAYER_3_INDICATOR MG_HSV_TO_BACKLIGHT_CONFIG_INDICATOR(MG_LAYER_3_COLOR, 254)

#undef RGB_BACKLIGHT_CAPS_LOCK_INDICATOR
// index = 253 to only light led under key that is mapped to KC_CAPS
// index = 252 to also light leds of all surrounding keys
#define RGB_BACKLIGHT_CAPS_LOCK_INDICATOR MG_HSV_TO_BACKLIGHT_CONFIG_INDICATOR(MG_LAYER_CAPSLOCK_COLOR, 252)

#define TAPPING_TERM 200

#ifdef RGBLIGHT_ENABLE
    #define RGB_DI_PIN A6
    #define RGBLED_NUM 16
  #ifndef MG_RGBLIGHT_EFFECT
    #define RGBLIGHT_ANIMATIONS
  #else
    #undef RGBLIGHT_ANIMATIONS
  #endif
    #define RGBLIGHT_LAYERS
    #define RGBLIGHT_LAYERS_OVERRIDE_RGB_OFF
#endif
