#pragma once

#undef RGB_BACKLIGHT_DISABLE_AFTER_TIMEOUT
#define RGB_BACKLIGHT_DISABLE_AFTER_TIMEOUT 3

#undef RGB_BACKLIGHT_DISABLE_WHEN_USB_SUSPENDED
#define RGB_BACKLIGHT_DISABLE_WHEN_USB_SUSPENDED 1

#undef RGB_BACKLIGHT_BRIGHTNESS
#define RGB_BACKLIGHT_BRIGHTNESS 100

/* enable/disable LEDs based on layout */
#undef RGB_BACKLIGHT_EFFECT
#define RGB_BACKLIGHT_EFFECT 5

#undef RGB_BACKLIGHT_EFFECT_SPEED
#define RGB_BACKLIGHT_EFFECT_SPEED 0

#undef RGB_BACKLIGHT_LAYER_1_INDICATOR
#define RGB_BACKLIGHT_LAYER_1_INDICATOR { .color = { .h = 85, .s = 255 }, .index = 255 }

#undef RGB_BACKLIGHT_LAYER_2_INDICATOR
#define RGB_BACKLIGHT_LAYER_2_INDICATOR { .color = { .h = 28, .s = 255 }, .index = 255 }

#undef RGB_BACKLIGHT_LAYER_3_INDICATOR
#define RGB_BACKLIGHT_LAYER_3_INDICATOR { .color = { .h = 128, .s = 255 }, .index = 255 }

#undef RGB_BACKLIGHT_CAPS_LOCK_INDICATOR
#define RGB_BACKLIGHT_CAPS_LOCK_INDICATOR { .color = { .h = 1, .s = 255 }, .index = 255 }

#define TAPPING_TERM 200

#ifdef RGBLIGHT_ENABLE
    #define RGB_DI_PIN A6
    #define RGBLED_NUM 16
    #define RGBLIGHT_ANIMATIONS
    #define RGBLIGHT_LAYERS
    #define RGBLIGHT_LAYERS_OVERRIDE_RGB_OFF
#endif
