#pragma once

#define MG_ORANGE 13, 255, 255

#ifdef RGBLIGHT_ENABLE
#define MG_BASE_COLOR MG_ORANGE
#else
#define MG_BASE_COLOR HSV_YELLOW
#endif

#define MG_LAYER_CAPSLOCK_COLOR HSV_RED
#define MG_LAYER_1_COLOR HSV_BLUE
#define MG_LAYER_2_COLOR HSV_PURPLE
#define MG_LAYER_3_COLOR HSV_MAGENTA

#define TAPPING_TERM 200

#ifdef RGBLIGHT_ENABLE
    #define RGBLIGHT_LAYERS
    #define RGBLIGHT_LAYERS_OVERRIDE_RGB_OFF
#endif
