#define ENCODERS_PAD_A { E6 }
#define ENCODERS_PAD_B { B7 }

#ifdef CONSOLE_ENABLE
    #undef RGBLIGHT_ANIMATIONS
#else
    #undef DISABLE_RGB_MATRIX_BAND_SAT
    #undef DISABLE_RGB_MATRIX_BAND_PINWHEEL_SAT
    #undef DISABLE_RGB_MATRIX_BAND_SPIRAL_SAT
    #undef DISABLE_RGB_MATRIX_RAINBOW_PINWHEELS
    #undef DISABLE_RGB_MATRIX_HUE_BREATHING
    #undef DISABLE_RGB_MATRIX_HUE_PENDULUM
    #undef DISABLE_RGB_MATRIX_HUE_WAVE

    #define RGB_MATRIX_STARTUP_MODE RGB_MATRIX_CYCLE_PINWHEEL
    #define RGB_MATRIX_FRAMEBUFFER_EFFECTS
    #define RGB_MATRIX_KEYPRESSES
#endif

#define RGB_MATRIX_DISABLE_AFTER_TIMEOUT 3
