OPT_DEFS += -DNO_SUSPEND_POWER_DOWN
EXTRAFLAGS += -flto

ENCODER_ENABLE = no
BOOTMAGIC_ENABLE = yes      # Virtual DIP switch configuration
CONSOLE_ENABLE = no
MOUSEKEY_ENABLE = yes
DEFERRED_EXEC_ENABLE = yes
