name: Merge upstream master
on:
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:

jobs:
  merge-upstream:
    runs-on: ubuntu-latest

    if: github.repository == 'mgor/qmk_firmware'

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: mgor
          fetch-depth: 0
      - name: Add upstream
        run: |
          git config --global user.email "github@mgor.se"
          git config --global user.name "Automated by Mikael Göransson"
          git remote add -f upstream https://github.com/qmk/qmk_firmware
          git remote -v
      - name: Fetch and merge upstream
        run: |
          git fetch upstream
          git merge --no-edit upstream/master | awk '/Already up to date/ {exit 1}' || exit 0
      - name: Push upstream changes
        run: |
          git push
